version: "3.9"

services:
  auth-service:
    build: ./auth-service
    

  catalog-service:
    build: ./catalog-service
    
  order-service:
    build: ./order-service
   

  notification-service:
    build: ./notification-service
    
