definitions:
  models.AddToCartRequest:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.PlaceOrderRequest:
    properties:
      address:
        type: string
      payment_method:
        type: string
    type: object
  models.UpdateCartRequest:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
      user_id:
        type: integer
    type: object
info:
  contact: {}
  description: This is the API for managing carts and orders in Savannah Store.
  title: Savannah Store API
  version: "1.0"
paths:
  /cart:
    delete:
      description: Removes a product from the cart. Users can delete items from their
        own cart. Admins can delete items from any user's cart by specifying user_id
        in query.
      parameters:
      - description: Product ID
        in: query
        name: product_id
        required: true
        type: integer
      - description: User ID (admin only)
        in: query
        name: user_id
        type: integer
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete item from cart
      tags:
      - Cart
    get:
      description: Retrieves all items from the user's cart.
      parameters:
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: unauthorized or invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: View cart
      tags:
      - Cart
    post:
      consumes:
      - application/json
      description: Adds a product to the user cart
      parameters:
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      - description: Cart item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AddToCartRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add item to cart
      tags:
      - Cart
    put:
      consumes:
      - application/json
      description: Updates quantity of an item in the cart. Users can update their
        own cart. Admins can update any user's cart by specifying user_id in request
        body.
      parameters:
      - description: Updated cart item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpdateCartRequest'
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update cart
      tags:
      - Cart
  /orders:
    delete:
      description: Deletes an order by ID. Users can delete their own orders. Admins
        can delete any order.
      parameters:
      - description: Order ID
        in: query
        name: order_id
        required: true
        type: integer
      - description: User ID (admin only)
        in: query
        name: user_id
        type: integer
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete order
      tags:
      - Order
    get:
      description: Retrieves all orders for the user. Admins can view all orders or
        specify a user_id query to view orders of a specific user.
      parameters:
      - description: User ID (admin only)
        in: query
        name: user_id
        type: integer
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: View orders
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: Places a new order for the user. Admins can place orders for other
        users by specifying user_id in request body.
      parameters:
      - description: Order details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.PlaceOrderRequest'
      - description: API Key
        in: header
        name: api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Place an order
      tags:
      - Order
swagger: "2.0"
